# Generated by Django 2.2.10 on 2020-07-12 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='модифицировано')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=2000, verbose_name='Ответ')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ANSWER_ANSWER_STATUS', to='checker.AnswerStatus', verbose_name='Статус проверки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
