# Generated by Django 2.2.10 on 2020-07-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='check_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор проверки'),
        ),
    ]
